version: '3.2'

services:
  openresty:
    image: openresty/openresty:alpine
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ./config:/etc/nginx/conf.d/
      - ./lua:/etc/nginx/lua

